server:
  port: 8088

spring:
  application:
    name: eureka-server

# 端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: peer1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      enable-self-preservation: false
    register-with-eureka: false
    fetch-registry: false
