server:
  port: 8091

spring:
  application:
    name: auth-server

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8088/eureka/
    fetch-registry: false

test:
  randomNum: ${random.value}