server:
  port: 8090

spring:
  application:
    name: producer-server

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8088/eureka/
